name: Python Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Instala webdriver manager
          pip install webdriver-manager

      # 4. Rodar os testes Selenium headless
      - name: Run tests
        run: |
          mkdir -p reports
          # Define variável de ambiente CI=true para ativar headless no seu driver
          export CI=true
          pytest --html=reports/report.html --self-contained-html -v

      # 5. Fazer upload do relatório
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html